**Tensor** - A mathematical object,extending scalars (single numbers),vectors (list of numbers) and Matrices (2D grids of numbers) to higher dimensions.

**Installing TensorFlow**                                                         
To install TensorFlow on your local machine you can use pip.

In [ ]:
pip install tensorflow

**Importing TensorFlow**                                                             
The first step here is going to be to select the correct version of TensorFlow from within collabratory!

In [ ]:
import tensorflow as tf  # now import the tensorflow module
print(tf.version)  # make sure the version is 2.x

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.12/dist-packages/tensorflow/_api/v2/version/__init__.py'>


Each tensor represents a partialy defined computation that will eventually produce a value. TensorFlow programs work by building a graph of Tensor objects that details how tensors are related. Running different parts of the graph allow results to be generated.

Each tensor has a data type and a shape.

Data Types Include: float32, int32, string and others.

Shape: Represents the dimension of data.

Just like vectors and matrices tensors can have operations applied to them like addition, subtraction, dot product, cross product etc.

**Creating Tensors**

Below is an example of how to create some different tensors.

You simply define the value of the tensor and the datatype and you are good to go! It's worth mentioning that usually we deal with tensors of numeric data, it is quite rare to see string tensors.

In [ ]:
string = tf.Variable("tensorflow", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

**Rank/Degree of Tensors**

Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. What we created above is a tensor of rank 0, also known as a scalar.

| Rank | What it means                | Example                   |
| ---- | ---------------------------- | ------------------------- |
| 0    | Just **one number**          | `5`                       |
| 1    | A **list** of numbers        | `[5, 10, 15]`             |
| 2    | A **table** (rows & columns) | `[[1, 2], [3, 4]]`        |
| 3    | A **cube** of numbers        | like a stack of 2D tables |
| 4+   | **Higher-dimensional** data  | images, videos, etc.      |


In [ ]:
rank0 = tf.constant(7)
tf.rank(rank0)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [ ]:
rank1 = tf.constant([1, 2, 3])
tf.rank(rank1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
rank2 = tf.constant([[1, 2, 3],[4, 5, 6]])
tf.rank(rank2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
rank3 = tf.constant([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])
tf.rank(rank3)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

**Shape of Tensors**

Now that we've talked about the rank of tensors it's time to talk about the shape. The shape of a tensor is simply the number of elements that exist in each dimension. TensorFlow will try to determine the shape of a tensor but sometimes it may be unknown.

To get the shape of a tensor we use the shape attribute.

In [ ]:
rank3.shape

TensorShape([2, 2, 2])

**Changing Shape**

The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convient to be able to change the shape of a tensor.

The example below shows how to change the shape of a tensor.

In [ ]:
reshaped_2d = tf.reshape(rank3, (4, 2))
print("Reshaped (4x2):\n", reshaped_2d)
print("Shape:", reshaped_2d.shape)


Reshaped (4x2):
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)
Shape: (4, 2)


###Types of Tensors
Before we go to far, I will mention that there are diffent types of tensors. These are the most used and we will talk more in depth about each as they are used.
- Variable
- Constant
- Placeholder
- SparseTensor

With the execption of ```Variable``` all these tensors are immuttable, meaning their value may not change during execution.

For now, it is enough to understand that we use the Variable tensor when we want to potentially change the value of our tensor.

